### ISSUE TITLE
Address inheritance of page objects

### ISSUE THREAD

**Issue by nvborisenko** [yapoml/yapoml#10]
Page object may have different representations depending on view port (desktop, mobile).

This library should address it.

Like `mypage.po.yaml`:
```yaml
ya:
  SomeComponent:
    by: abc
```

And mobile version `mypage.mobile.po.yaml`:
```yaml
ya:
  SomeComponent:
    by: mobile_abc
```

On consumer side it should possible to define which version of page to return from space.
