### ISSUE TITLE
Introduce waiter/should/when

### ISSUE THREAD

**Issue by nvborisenko** [yapoml/yapoml#19]
Would be nice to see fluent waiters
```yaml
MyForm
  by: .//form
  MyButton: .//button
```

And then like
```csharp
driver.Ya().MyPage.MyForm.MyButton.When(it => it.IsDisplayed()).Click();
```

Syntax can be any, IntelliSense is important.
