### ISSUE TITLE
Introduce And keyword for fluent api

### ISSUE THREAD

**Issue by nvborisenko** [yapoml/yapoml#24]
Given that `Login.page.yaml`

```
form:
  by: ./form

  username: .user
  password: id pass
```

We can fill in form typing less code

```csharp
driver.Ya().LoginPage.Form.Username.Type("user01")
  .And.Password.Type("123456")
  .And.Form.Submit();
```

where `And` provides an access to all sibling components and all recursive parents.
