### ISSUE TITLE
If component has no nested components then we can generate parental as nested

### ISSUE THREAD

**Issue by nvborisenko** [yapoml/yapoml#25]
```yaml
form:
  by: .//form

  username: .username
  password: .password
  
  sign in: .//button
```

```csharp
driver.Ya().LoginPage.Form
  .Username.Type("user01")
  .And.Password.Type("pass01")
  .And.SignIn.Click();
```

we can even simplify fluent api
```csharp
driver.Ya().LoginPage.Form
  .Username.Type("user01")
  .Password.Type("pass01")
  .SignIn.Click();
```
