### ISSUE TITLE
Chaining locators

### ISSUE THREAD

**Issue by nvborisenko** [yapoml/yapoml#32]
```yaml
A:
  by: //div1
  
  B:
    by: ./div2
```

When we write `page.A.B.Click()` then
- locating of `A` can be skipped
- `B` can be located by `//div1/div2`

Note: some locators cannot be chained, like if B has `//div2`
