### ISSUE TITLE
Simplify yet another components definition in page 

### ISSUE THREAD

**Issue by nvborisenko** [yapoml/yapoml#9]
```yaml
MyButton:
  by:
    css: .primary
```

is the equivalent to
```yaml
MyButton:
  by: css .primary
```

and in many cases it can be even simplified to
```yaml
MyButton: by css .primary
```

and
```yaml
MyButton: css .primary
```

and
```yaml
MyButton: .primary # generator will resolve which by method is default
```
